name = "phanes"
env = "dev"
version = "0.1.0"
[http]
http_listen = ":7771"
validate_trans = "zh"

[grpc]
grpc_listen = ":9090"
discovery_listen = ""
validate_trans = "zh"

[[db]]
enabled = false
addr = "host=127.0.0.1 user=root password=root dbname=phanes port=5432 sslmode=disable TimeZone=Asia/Shanghai"
pwd = "root"
type = "postgres"
user = "root"

[[db]]
enabled = false
addr = "127.0.0.1:6379"
pwd = ""
type = "redis"
user = ""

[broker]
enabled = false
addr = "amqp://coco:kk123123123@127.0.0.1:5672/"
pwd = ""
type = "rabbitmq"
user = ""

[collect.log]
file_name = "admin"
prefix = "【Phanes】"

[collect.log.redis]
addr = ""
pwd = ""
redis_key = "log_list"

[collect.metric]
enabled = false
addr = ""

[collect.trace]
enabled = false
addr = ""

[proxy]
domain = "http://127.0.0.1"
prefix = "/phanes"

[traefik]
domain = "test.com"
enabled = false
prefix = "/phanes"

[id_gen]
type = 1
node = 1
